# 02 넘파이

## 2.1 넘파이 소개

In [19]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [21]:
import numpy as np
data=[1,2,3]  # 리스트
print(data)
arr=np.array(data)  # ndarray
print(arr)
print(type(arr))

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
data=[1,2,3]

result=[]
for i in data:
    result.append(i*10)
print(result)

[10, 20, 30]


In [6]:
import numpy as np

arr=np.array([1,2,3])
result=arr*10
print(result)

[10 20 30]


In [7]:
data2d=[[1,2,3],
       [4,5,6],
       [7,8,9]]
print(data2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
import numpy as np

data2d=[[1,2,3],
       [4,5,6],
       [7,8,9]]
arr=np.array(data2d)
print(arr[:,0])

[1 4 7]


## 2.2 ndarray

In [10]:
data1=[1,2,3,4]

arr1=np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
data2=[[1,2],
      [3,4]]
arr2=np.array(data2)
print(arr2)
print(type(arr2))
print(type(arr2[0]))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [15]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 2)
2
int32


In [16]:
print(arr1.shape)

(4,)


In [17]:
data=[[1],
     [2],
     [3],
     [4]]
c=np.array(data)
print(c.shape)

(4, 1)


In [18]:
print(np.zeros(3))
print(np.ones(3))

[0. 0. 0.]
[1. 1. 1.]


In [19]:
size=(3,4)
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
print(np.arange(5))
print(np.arange(1,5))
print(np.arange(1,5,2))

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [23]:
ndarr1=np.arange(6)
ndarr2=ndarr1.reshape(2,3)
print(ndarr2)

[[0 1 2]
 [3 4 5]]


## 2.3 데이터 타입

In [25]:
arr=np.array([1,2,3], dtype=np.uint8)
print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


In [26]:
arr=arr.astype('int8')
print(arr.dtype)

int8


In [27]:
a=np.array([0,255], dtype=np.uint8)
b=a.astype('int8')  # -128~127까지만 표현되므로 255를 표현할 수 없음
print(a)
print(b)

[  0 255]
[ 0 -1]


In [29]:
a16=np.array([1.333333],dtype=np.float16)
a32=np.array([1.333333],dtype=np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [30]:
a16=np.array([1.0], dtype=np.float16)
a32=np.array([1.0], dtype=np.float32)
print(a16/3)
print(a32/3)

[0.3333]
[0.33333334]


In [31]:
print(np.nan, type(np.nan))
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [22]:
arr=np.array([-1,2,-3])
print(arr/0)  # 경고 및 결과값은 무한대

[-inf  inf -inf]


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_8364\2565207972.py:2: RuntimeWarning: divide by zero encountered in divide
  print(arr/0)  # 경고 및 결과값은 무한대


In [33]:
arr=np.array([-1,2,-3])
print(arr+np.nan)
print(arr+np.inf)

[nan nan nan]
[inf inf inf]


## 2.4 인덱싱과 슬라이싱

In [28]:
arr=np.arange(4)
print(arr[0])

0


In [29]:
arr=np.arange(4).reshape(2,2)  # reshape메서드로 2행2열로 변환
print(arr[0])

[0 1]


In [30]:
print(arr[0][0])

0


In [31]:
print(arr[0][0])
print(arr[0, 0])

0
0


In [32]:
a=np.arange(10000).reshape(100,100)
%timeit a[0,50]

203 ns ± 45 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [33]:
a=np.arange(10000).reshape(100,100)
%timeit a[0][50]

379 ns ± 6.19 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [41]:
arr=np.arange(4)
print(arr[:2])

[0 1]


In [35]:
target=[0,2]
print(arr[target])

[0 2]


In [36]:
print(arr[[0,2]])

[0 2]


In [44]:
arr=np.arange(20).reshape(4,5)
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [45]:
# 왼쪽 끝의 두 개 컬럼을 슬라이싱 - 리스트에 값을 저장하는 번거러움
result=[]
for row in arr:
    row_01=[row[0], row[1]]
    result.append(row_01)
print(result)

[[0, 1], [5, 6], [10, 11], [15, 16]]


In [46]:
# ndarry는 한 번에 컬럼의 슬라이싱
print(arr[:,:2])

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]


In [47]:
# 일부 영역 슬라이싱
print(arr[1:4, 2:5])
print(arr[1:, 2:])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## 2.5 브로드캐스팅

In [48]:
# ndarray간의 연산으로 확장
a=np.array([1,2,3])
b=np.array([2,3,4])
print(a+b)
print(a*b)
print(a%b)

[3 5 7]
[ 2  6 12]
[1 2 3]


In [55]:
high=[92700,92400,92100,94300,92300]
low=[90000,91100,91700,92100,90900]

arr_high=np.array(high)
arr_low=np.array(low)

arr_diff=arr_high-arr_low
print(arr_diff)

[2700 1300  400 2200 1400]


In [57]:
arr_high_x3=arr_high*3
arr_low_x2=arr_low*2
print(arr_high_x3+arr_low_x2)

[458100 459400 459700 467100 458700]


In [58]:
avg=(arr_high*3)+(arr_low*2)

In [59]:
data=[[92700,92400,92100,94300,92300],
      [90000,91100,91700,92100,90900]]
arr=np.array(data)
print(arr[0]*3 + arr[1] * 2)

[458100 459400 459700 467100 458700]


In [60]:
weight=np.array([3,2]).reshape(2,1)
print((weight*arr).sum(axis=0))

[458100 459400 459700 467100 458700]


## 2.6 조건 연산

In [61]:
arr=np.array([10,20,30])
print(arr>10)

[False  True  True]


In [62]:
arr=np.array([10,20,30])
cond=[False, True, True]
print(arr[cond])

[20 30]


In [63]:
arr=np.array([10,20,30])
print(arr[[False,True,True]])

[20 30]


In [64]:
arr=np.array([10,20,30])
cond=arr>10
print(arr[cond])

[20 30]


In [65]:
print(arr[arr>10])

[20 30]


In [67]:
cond.all()  # 모든 값이 참일 경우

False

In [68]:
cond.any()  # 하나다로 참일 경우

True

In [69]:
arr=np.array([10,20,30])
cond0=arr>10
cond1=arr<30
print(arr[cond0*cond1])

[20]


In [71]:
arr=np.array([10,20,30])
print(arr[(arr>10)&(arr<30)])

[20]


In [73]:
arr=np.array([10,20,30])
cond=arr>10
arr[cond]=1
arr[~cond]=0  # not(~) 연산자
print(arr)

[0 1 1]


In [74]:
arr=np.array([10,20,30])
arr=np.where(arr>10,1,0)
print(arr)

[0 1 1]


In [75]:
cond=arr>10
arr[cond]=arr[cond]+10
arr[~cond]=arr[~cond]-10

In [76]:
arr=np.where(arr>10,arr+10,arr-10)

In [77]:
lge=np.array([93000,82400,99100,81000,72300])

In [78]:
result=lge[lge<=85000]
print(len(result))

3


## 2.7 함수와 메서드

In [79]:
arr=np.arange(8).reshape(4,2)
print(arr.sum())

28


In [80]:
print(arr.sum(axis=0))

[12 16]


In [81]:
print(arr.sum(axis=1))

[ 1  5  9 13]


In [82]:
np.random.randint(3)

1

In [83]:
np.random.randint(46, size=5)
np.random.randint(46, size=(2,5))

array([[17, 10, 25, 11,  4],
       [40, 13, 11, 11, 12]])

In [84]:
x=np.linspace(0,10,3)
print(x)

[ 0.  5. 10.]


In [85]:
y=x**2

In [86]:
a=np.arange(4)
b=np.arange(4,8)
c=np.vstack([a,b])
print(c)

[[0 1 2 3]
 [4 5 6 7]]


# 03 판다스 시리즈

## 3.1 시리즈 소개

In [49]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


## 3.2 시리즈 생성

In [87]:
from pandas import Series

data=[10,20,30]
s=Series(data)  # 시리즈 객체 생성시 리스트 객체를 초기화 인자로 넘겨줌
print(s)

0    10
1    20
2    30
dtype: int64


In [88]:
from pandas import Series
import numpy as np

data=np.arange(5)
s=Series(data)  # 시리즈 객체 생성시 ndarry 객체를 초기화 인자로 넘겨줌
print(s)

0    0
1    1
2    2
3    3
4    4
dtype: int32


In [89]:
data=["시가","고가"]
s=Series(data)
print(s)

0    시가
1    고가
dtype: object


In [90]:
s=Series(['samsung',81000])
print(s)

0    samsung
1      81000
dtype: object


## 3.3 시리즈 인덱스

In [91]:
from pandas import Series

data=[1000,2000,3000]
s=Series(data)  # 인덱스 미설정시 0부터 시작하는 RangeIndex타입으로 생성
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [93]:
data=[1000,2000,3000]
s=Series(data)
s.index=['메로나','구구콘','하겐다즈']
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [94]:
data=[1000,2000,3000]
index=['메로나','구구콘','하겐다즈']

s=Series(data,index)  # 데이터와 인덱스
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [50]:
data=[1000,2000,3000]
index=['메로나','구구콘','하겐다즈']

s=Series(data=data,index=index)  # 명시적 파라미터
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [96]:
v=[1000,2000,3000]
k=['메로나','구구콘','하겐다즈']

s=Series(data=v,index=k)

In [97]:
s=Series(data, index)
s=Series(data, index=index)
s=Series(data=data, index=index)
s=Series(index=index, data=data)

In [51]:
data=[1000,2000,3000]
index=['메로나','구구콘','하겐다즈']

s=Series(data=data,index=index)
s2=s.reindex(["메로나","비비빅","구구콘"])  # reindex메서드 사용시 기존에 있던 인덱스는 기존 값을 사용하고, 새로운 인덱스는 NaN
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [52]:
print(s2.fillna(0))  # fillna 는 NaN을 0으로 변경

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [103]:
s2=s.reindex(["메로나","비비빅","구구콘"], fill_value=0)  # reindex메서드 사용시 fill_value파라미터로 한번에 처리

In [104]:
price=[42500,42550,41800,42550,42650]
date=["2019-05-31","2019-05-30","2019-05-29","2019-05-28","2019-05-27"]
s=Series(price, date)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [105]:
# 딕셔너리를 사용해 시리즈를 한 번에 생성 - 딕셔너리의 key가 시리즈의 인덱스로, value가 데이터로 구성
data={
    "2019-05-31":42500,
    "2019-05-30":42550,
    "2019-05-29":41800,
    "2019-05-28":42550,
    "2019-05-27":42650,
}
s=Series(data)

In [106]:
print(s.index)
print(s.index.dtype)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='object')
object


In [107]:
print(s.values)

[42500 42550 41800 42550 42650]


## 3.4 시리즈 인덱싱

In [54]:
from pandas import Series

data=[1000,2000,3000]
s=Series(data=data)  # index 미지정

print(s.iloc[0])
print(s.iloc[1])
print(s.iloc[2])
print(s.iloc[-1])

1000
2000
3000
3000


In [55]:
# loc는 인덱스 값을 통해 인덱싱
print(s.loc[1])
print(s.loc[2])
print(s.loc[-1])  # 에러

2000
3000


KeyError: -1

In [ ]:
data=[1000,2000,3000]
index=["메로나","구구콘","하겐다즈"]
s=Series(data=data, index=index)

print(s.iloc[0])
print(s.loc['메로나'])

In [56]:
s1=Series([10,20,30])
s2=Series([10,20,30], index=[1,2,3])
print(s1[0])
print(s2[0])  # 에러

10


KeyError: 0

In [57]:
s3=Series([10,20,30], index=['a','b','c'])
print(s3[0])

10


In [58]:
print(s3.index[0])
print(s3.index[-1])

a
c


## 3.5 시리즈 슬라이싱

In [121]:
from pandas import Series

data=[1000,2000,3000]
index=["메로나","구구콘","하겐다즈"]
s=Series(data=data, index=index)
print(s.iloc[0:2])

메로나    1000
구구콘    2000
dtype: int64


In [122]:
data=[1000,2000,3000]
index=["메로나","구구콘","하겐다즈"]
s=Series(data=data,index=index)

print(s.loc['메로나':'구구콘'])

메로나    1000
구구콘    2000
dtype: int64


In [124]:
data=[1000,2000,3000]
index=["메로나","구구콘","하겐다즈"]
s=Series(data=data,index=index)

indice=[0,2]
print(s.iloc[indice])
print(s.iloc[[0,2]])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


In [126]:
data=[1000,2000,3000]
index=["메로나","구구콘","하겐다즈"]
s=Series(data=data,index=index)

indice=['메로나','하겐다즈']  # 문자열 인덱스는 loc로 슬라이싱
print(s.loc[indice])
print(s.loc[['메로나','하겐다즈']])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


## 3.6 시리즈 수정/추가/삭제

In [127]:
from pandas import Series

data=[1000,2000,3000]
index=["메로나","구구콘","하겐다즈"]
s=Series(data=data,index=index)

s.loc['메로나']=500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
dtype: int64


In [128]:
s.iloc[0]=500
s['메로나']=500

In [129]:
s.loc['비비빅']=500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [130]:
print(s.drop('메로나'))
print(s.drop(0))  #에러

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


KeyError: '[0] not found in axis'

In [131]:
s=s.drop('메로나')
print(s)

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


## 3.7 시리즈 연산

In [2]:
from pandas import Series

철수=Series([10,20,30], index=['NAVER','SKT','KT'])
영희=Series([10,30,20], index=['SKT','KT','NAVER'])
가족=철수+영희
print(가족)

KT       60
NAVER    30
SKT      30
dtype: int64


In [3]:
print(철수*10)

NAVER    100
SKT      200
KT       300
dtype: int64


In [4]:
high=Series([42800,42700,42050,42950,43000])
low=Series([42150,42150,41300,42150,42350])

diff=high-low
print(diff)

0    650
1    550
2    750
3    800
4    650
dtype: int64


In [5]:
print(diff.max())

800


In [6]:
date=['6/1','6/2','6/3','6/4','6/5']
high=Series([42800,42700,42050,42950,43000], index=date)
low=Series([42150,42150,41300,42150,42350], index=date)
diff=high-low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [7]:
max_idx=0
max_val=0

for i in range(len(diff)):
    if diff[i]>max_val:
        max_val=diff[i]
        max_idx=i
        
print(max_idx)
print(diff.index[max_idx])

3
6/4


In [8]:
print(diff.idxmax())
print(diff.idxmin())

6/4
6/2


In [9]:
date=['6/1','6/2','6/3','6/4','6/5']
high=Series([42800,42700,42050,42950,43000], index=date)
low=Series([42150,42150,41300,42150,42350], index=date)
profit=high/low
print(profit)

6/1    1.015421
6/2    1.013049
6/3    1.018160
6/4    1.018980
6/5    1.015348
dtype: float64


In [10]:
print(profit.cumprod())  # 반복문 대신 cumprod메서드를 사용하여 누적 수익률 계산

6/1    1.015421
6/2    1.028671
6/3    1.047351
6/4    1.067230
6/5    1.083610
dtype: float64


In [11]:
print(profit.cumprod().iloc[-1])

1.0836101509172456


In [12]:
data={
    "삼성전자":"전기,전자",
    "LG전자":"전기,전자",
    "현대차":"운수장비",
    "NAVER":"서비스업",
    "카카오":"서비스업"
}
s=Series(data)

In [13]:
print(s.unique())

['전기,전자' '운수장비' '서비스업']


In [14]:
s.value_counts()

전기,전자    2
서비스업     2
운수장비     1
Name: count, dtype: int64

## 3.8 시리즈와 Map

In [15]:
from pandas import Series
s=Series(["1,234", "5,678", "9,876"])
print(int(s))  # 형변환 에러

TypeError: cannot convert the series to <class 'int'>

In [16]:
def remove_comma(x):
    print(x, 'in function')
    return x

s=Series(["1,234", "5,678", "9,876"])
result=s.map(remove_comma)  # remove_comma 함수를 map 메서드로 연결
print(result)

1,234 in function
5,678 in function
9,876 in function
0    1,234
1    5,678
2    9,876
dtype: object


In [18]:
from pandas import Series

def remove_comma(x):
    return int(x.replace(",",""))

s=Series(["1,234", "5,678", "9,876"])
result=s.map(remove_comma)
print(result)

0    1234
1    5678
2    9876
dtype: int64


In [19]:
def is_greater_than_5000(x):
    if x > 5000:
        return "크다"
    else:
        return "작다"

s=Series([1234, 5678, 9876])
s=s.map(is_greater_than_5000)
print(s)

0    작다
1    크다
2    크다
dtype: object


## 3.9 시리즈 필터링

In [2]:
from pandas import Series

data=[42500, 42550, 41800, 42550, 42650]
index=['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s=Series(data=data,index=index)
cond=s>42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [3]:
print(s[cond])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [4]:
close=[42500,42550,41800,42550,42650]
open=[42600,42200,41850,42550,42500]
index=['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
open=Series(data=open, index=index)
close=Series(data=close, index=index)

cond=close>open
print(cond)

2019-05-31    False
2019-05-30     True
2019-05-29    False
2019-05-28    False
2019-05-27     True
dtype: bool


In [5]:
print(close[cond])

2019-05-30    42550
2019-05-27    42650
dtype: int64


In [6]:
print(close[close>open])

2019-05-30    42550
2019-05-27    42650
dtype: int64


In [7]:
print(close.index[close>open])
print(close[close>open].index)

Index(['2019-05-30', '2019-05-27'], dtype='object')
Index(['2019-05-30', '2019-05-27'], dtype='object')


In [8]:
close=[42500,42550,41800,42550,42650]
open=[42600,42200,41850,42550,42500]
index=['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open=Series(data=open, index=index)
close=Series(data=close, index=index)
diff=close-open
print(diff[close>open])

2019-05-30    350
2019-05-27    150
dtype: int64


## 3.10 정렬 및 순위

In [12]:
from pandas import Series

data=[3.1,2.0,10.1,5.1]
index=['000010','000020','000030','000040']
s=Series(data=data,index=index)
print(s)

# 정렬(오름차순)
s1=s.sort_values()
print(s1)

# 정렬(내림차눗)
s2=s.sort_values(ascending=False)
print(s2)

000010     3.1
000020     2.0
000030    10.1
000040     5.1
dtype: float64
000020     2.0
000010     3.1
000040     5.1
000030    10.1
dtype: float64
000030    10.1
000040     5.1
000010     3.1
000020     2.0
dtype: float64


In [15]:
data=[3.1,2.0,10.1,5.1]
index=['000010','000020','000030','000040']
s=Series(data=data,index=index)
print(s.rank())  # rank메서드는 값이 작은 데이터를 1순위로 지정 (동일한 값을 갖는 데이터의 순위 표현 위해 rank값은 float64)

000010    2.0
000020    1.0
000030    4.0
000040    3.0
dtype: float64


In [16]:
print(s.rank(ascending=False))  # 값이 큰 데이터를 1등으로 지정

000010    3.0
000020    4.0
000030    1.0
000040    2.0
dtype: float64


# 04 판다스 데이터프레임 Part1

# 4.1 데이터프레임 소개 및 생성

In [59]:
# [방법1] 딕셔너리로 데이터프레임을 생성
from pandas import DataFrame

data={
    '종목코드':['037730','036360','005760'],
    '종목명':['3R','3SDFT','ACTS'],
    '현재가':[1510,1790,1185]
}

df=DataFrame(data)  # DataFrame 클래스의 객체 생성(생성자 호출)
print(df)

     종목코드    종목명   현재가
0  037730     3R  1510
1  036360  3SDFT  1790
2  005760   ACTS  1185


In [64]:
# [방법2] 리스트로 데이터프레임을 생성
from pandas import DataFrame

data=[
    ["037730","3R",1510],
    ["036360","3SOFT",1790],
    ["005760","ACTS",1185],
]
columns=["종목코드","종목명","현재가"]

df=DataFrame(data=data,columns=columns)
print(df)

     종목코드    종목명   현재가
0  037730     3R  1510
1  036360  3SOFT  1790
2  005760   ACTS  1185


In [67]:
# [방법3] 리스트와딕셔너리로 데이터프레임을 생성
from pandas import DataFrame

data=[
    {"종목코드":"037730","종목명":"3R","현재가":1510},
    {"종목코드":"036360","종목명":"3SOFT","현재가":1790},
    {"종목코드":"005760","종목명":"ACTS","현재가":1185},
]

df=DataFrame(data=data)
print(df)

     종목코드    종목명   현재가
0  037730     3R  1510
1  036360  3SOFT  1790
2  005760   ACTS  1185


## 4.2 데이터프레임의 인덱스

In [68]:
from pandas import DataFrame

data=[
    ["037730","3R",1510,7.63],
    ["036360","3SOFT",1790,1.65],
    ["005760","ACTS",1185,1.28]
]
columns=["종목코드","종목명","현재가","등락률"]

df=DataFrame(data=data,columns=columns)
print(df)

     종목코드    종목명   현재가   등락률
0  037730     3R  1510  7.63
1  036360  3SOFT  1790  1.65
2  005760   ACTS  1185  1.28


In [71]:
from pandas import DataFrame

data=[
    ["037730","3R",1510,7.63],
    ["036360","3SOFT",1790,1.65],
    ["005760","ACTS",1185,1.28]
]
columns=["종목코드","종목명","현재가","등락률"]

df=DataFrame(data=data,columns=columns)
df=df.set_index('종목코드')  #인덱스 설정하고 수정된 데이터프레임 객체를 리턴
print(df)

          종목명   현재가   등락률
종목코드                     
037730     3R  1510  7.63
036360  3SOFT  1790  1.65
005760   ACTS  1185  1.28


In [74]:
from pandas import DataFrame

data=[
    ["3R",1510,7.63],
    ["3SOFT",1790,1.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]

df=DataFrame(data=data,index=index, columns=columns)
df.index_name="종목코드"
print(df)

          종목명   현재가   등락률
037730     3R  1510  7.63
036360  3SOFT  1790  1.65
005760   ACTS  1185  1.28


## 4.3 컬럼 인덱싱

In [75]:
from pandas import DataFrame

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)
print(df['현재가'])

037730    1510
036360    1790
005760    1185
Name: 현재가, dtype: int64


In [76]:
print(df.현재가)

037730    1510
036360    1790
005760    1185
Name: 현재가, dtype: int64


In [77]:
리스트=["현재가","등락률"]
df[리스트]

현재가   등락률
037730  1510  7.36
036360  1790  4.65
005760  1185  1.28

In [78]:
print(df[["현재가","등락률"]])

         현재가   등락률
037730  1510  7.36
036360  1790  4.65
005760  1185  1.28


In [82]:
df["현재가"]  # 한 개의 열만 인덱싱하면 시리즈 객체를 가져옴

037730    1510
036360    1790
005760    1185
Name: 현재가, dtype: int64

In [83]:
df[["현재가"]]  # 리스트로 슬라이싱하면 데이터프레임을 가져옴

현재가
037730  1510
036360  1790
005760  1185

## 4.4 로우 인덱싱

In [86]:
from pandas import DataFrame

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)
print(df.loc['037730'])  # loc속성으로 문자열 인덱스 "037730"에 대응하는 로우 데이터를 인덱싱

종목명      3R
현재가    1510
등락률    7.36
Name: 037730, dtype: object


In [88]:
print(df.iloc[0])
print(df.iloc[-1])

종목명      3R
현재가    1510
등락률    7.36
Name: 037730, dtype: object
종목명    ACTS
현재가    1185
등락률    1.28
Name: 005760, dtype: object


In [89]:
print(df.loc[["037730","036360"]])
print(df.iloc[[0,1]])

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  4.65
          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  4.65


## 4.5 특정 값 가져오기

In [90]:
from pandas import DataFrame

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)

print(df.iloc[0])
print(df.loc["037730"])

종목명      3R
현재가    1510
등락률    7.36
Name: 037730, dtype: object
종목명      3R
현재가    1510
등락률    7.36
Name: 037730, dtype: object


In [92]:
# 행 번호로 행 선택 후 시리즈 인덱싱
print(df.iloc[0].iloc[1])  # 시리즈 행 번호
print(df.iloc[0].loc["현재가"])  # 시리즈 인덱스
print(df.iloc[0]["현재가"])  # 시리즈 인덱스

# 인덱스로 행 선택 후 시리즈 인덱싱
print(df.loc["037730"].iloc[1])  # 시리즈 행 번호
print(df.loc["037730"].loc["현재가"])  # 시리즈 인덱스
print(df.loc["037730"]["현재가"])  # 시리즈 인덱스

1510
1510
1510
1510
1510
1510


In [93]:
print(df.loc["037730","현재가"])
print(df.iloc[0,1])

1510
1510


In [94]:
print(df['현재가'].iloc[0])
print(df['현재가'].loc["037730"])
print(df['현재가']["037730"])

1510
1510
1510


## 4.6 특정 범위 가져오기

In [96]:
from pandas import DataFrame

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)

print(df.loc[["037730","036360"]])
print(df.iloc[[0,1]])

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  4.65
          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  4.65


In [97]:
df=df.loc[["037730","036360"]]
df=df[["종목명","현재가"]]
print(df)

          종목명   현재가
037730     3R  1510
036360  3SOFT  1790


In [98]:
print(df.loc[["037730","036360"],["종목명","현재가"]])
print(df.iloc[[0,1],[0,1]])

          종목명   현재가
037730     3R  1510
036360  3SOFT  1790
          종목명   현재가
037730     3R  1510
036360  3SOFT  1790


## 4.7 데이터프레임 필터링

In [99]:
from pandas import DataFrame

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)

cond=df['현재가'] >= 1400
print(df.loc[cond])

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  4.65


In [100]:
cond=df['현재가'] >= 1400
print(df.loc[cond]["현재가"])
print(df.loc[cond,"현재가"])

037730    1510
036360    1790
Name: 현재가, dtype: int64
037730    1510
036360    1790
Name: 현재가, dtype: int64


In [101]:
cond=(df['현재가'] >= 1400)&(df['현재가'] < 1700)
print(df.loc[cond])

       종목명   현재가   등락률
037730  3R  1510  7.36


In [102]:
cond=df['현재가'] >= (1400 & df['현재가']) < 1700  # 에러 - 연산자 우선순위가 &가 더 높기 때문에 괄호 사용 필요

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [105]:
cond=(df['현재가'] >= 1400) & (df['현재가'] < 1700)
print(df.loc[~cond])

          종목명   현재가   등락률
036360  3SOFT  1790  4.65
005760   ACTS  1185  1.28


## 4.8 컬럼 추가하기

In [106]:
from pandas import DataFrame, Series

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)

s=Series(data=[1600,1600,1600], index=df.index)
df['목표가']=s
print(df)

          종목명   현재가   등락률   목표가
037730     3R  1510  7.36  1600
036360  3SOFT  1790  4.65  1600
005760   ACTS  1185  1.28  1600


In [107]:
df['목표가']=1600
print(df)

          종목명   현재가   등락률   목표가
037730     3R  1510  7.36  1600
036360  3SOFT  1790  4.65  1600
005760   ACTS  1185  1.28  1600


In [109]:
df["괴리율"]=(df["목표가"]-df["현재가"])/df["현재가"]
print(df)

          종목명   현재가   등락률   목표가       괴리율
037730     3R  1510  7.36  1600  0.059603
036360  3SOFT  1790  4.65  1600 -0.106145
005760   ACTS  1185  1.28  1600  0.350211


## 4.9 로우 추가하기

In [110]:
from pandas import DataFrame

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)

In [111]:
from pandas import Series

s=Series(data=["LG전자",60000,3.84], index=df.columns)
df.loc["066570"]=s
print(df)

          종목명    현재가   등락률
037730     3R   1510  7.36
036360  3SOFT   1790  4.65
005760   ACTS   1185  1.28
066570   LG전자  60000  3.84


In [112]:
df.loc["066570"]=["LG전자",60000,3.84]
print(df)

          종목명    현재가   등락률
037730     3R   1510  7.36
036360  3SOFT   1790  4.65
005760   ACTS   1185  1.28
066570   LG전자  60000  3.84


In [117]:
s=Series(data=["LG전자",60000,3.84], index=df.columns, name="066570")
new_df=df.append(s)  # pandas 2.0.0 이후부터 append() 메서드 사용 불가
print(new_df)

AttributeError: 'DataFrame' object has no attribute 'append'

## 4.10 컬럼/로우 삭제하기

In [123]:
from pandas import DataFrame

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)

df_new=df.drop("현재가", axis=1)
print(df)
print(df_new)

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  4.65
005760   ACTS  1185  1.28
          종목명   등락률
037730     3R  7.36
036360  3SOFT  4.65
005760   ACTS  1.28


In [124]:
df_new=df.drop("037730", axis=0)
print(df)
print(df_new)

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  4.65
005760   ACTS  1185  1.28
          종목명   현재가   등락률
036360  3SOFT  1790  4.65
005760   ACTS  1185  1.28


In [121]:
df.drop("037730", axis=0, inplace=True)  # 원본 데이터프레임 변경
print(df)

          종목명   현재가   등락률
036360  3SOFT  1790  4.65
005760   ACTS  1185  1.28


In [125]:
df.drop(["037730","005760"], axis=0, inplace=True)
print(df)

          종목명   현재가   등락률
036360  3SOFT  1790  4.65


## 4.11 컬럼 레이블 변경

In [126]:
from pandas import DataFrame

data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)

print(df.columns)
print(df.index)

Index(['종목명', '현재가', '등락률'], dtype='object')
Index(['037730', '036360', '005760'], dtype='object')


In [128]:
df.columns=['name','close','fluctuation']
df.index.name='code'
print(df)

         name  close  fluctuation
code                             
037730     3R   1510         7.36
036360  3SOFT   1790         4.65
005760   ACTS   1185         1.28


In [129]:
data=[
    ["3R",1510,7.36],
    ["3SOFT",1790,4.65],
    ["ACTS",1185,1.28]
]

index=["037730","036360","005760"]
columns=["종목명","현재가","등락률"]
df=DataFrame(data=data,index=index,columns=columns)
df.rename(columns={'종목명':'code'}, inplace=True)
print(df)

         code   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  4.65
005760   ACTS  1185  1.28


## 4.12 데이터 타입 변경

In [134]:
from pandas import DataFrame

data=[
    ["1,000", "1,100", "1,510"],
    ["1,410", "1,420", "1,790"],
    ["850", "900", "1,185"],
]
columns=["03/02","03/03","03/04"]
df=DataFrame(data=data, columns=columns)
print(df)

   03/02  03/03  03/04
0  1,000  1,100  1,510
1  1,410  1,420  1,790
2    850    900  1,185


In [132]:
# 코드생략
def remove_comma(x):
    return int(x.replace(',',''))

df['03/02']=df['03/02'].map(remove_comma)
df['03/03']=df['03/03'].map(remove_comma)
df['03/04']=df['03/04'].map(remove_comma)
print(df)

   03/02  03/03  03/04
0   1000   1100   1510
1   1410   1420   1790
2    850    900   1185


In [135]:
# 코드생략
def remove_comma(x):
    return int(x.replace(',',''))

df=df.applymap(remove_comma)
print(df)
print(df.dtypes)

   03/02  03/03  03/04
0   1000   1100   1510
1   1410   1420   1790
2    850    900   1185
03/02    int64
03/03    int64
03/04    int64
dtype: object


In [136]:
import numpy as np
from pandas import DataFrame

def remove_comma(x):
    return int(x.replace(',',''))

data=[
    ["1,000", "1,100", "1,510"],
    ["1,410", "1,420", "1,790"],
    ["850", "900", "1,185"],
]

columns=["03/02","03/03","03/04"]
df=DataFrame(data=data, columns=columns)
df=df.applymap(remove_comma)
df=df.astype({"03/02":np.int64, "03/03":np.int64, "03/04":np.int64})
print(df.dtypes)

03/02    int64
03/03    int64
03/04    int64
dtype: object


## 4.13 컬럼의 문자열 다루기

In [141]:
from pandas import DataFrame
import numpy as np

data=[
    {"cd":"A060310", "nm":"3S", "close":"2,920"},
    {"cd":"A095570", "nm":"AJ네트웍스", "close":"6,250"},
    {"cd":"A006840", "nm":"AK홀딩스", "close":"29,700"},
    {"cd":"A054260", "nm":"APK홀딩스", "close":"19,400"}
]
df=DataFrame(data=data)
df

cd      nm   close
0  A060310      3S   2,920
1  A095570  AJ네트웍스   6,250
2  A006840   AK홀딩스  29,700
3  A054260  APK홀딩스  19,400

In [142]:
df['cd']=df['cd'].str[1:]

In [143]:
df['close']=df['close'].str.replace(',','').astype(np.int64)
df

cd      nm  close
0  060310      3S   2920
1  095570  AJ네트웍스   6250
2  006840   AK홀딩스  29700
3  054260  APK홀딩스  19400

# 05 판다스 데이터프레밍 Part2

## 5.1 Query

In [144]:
from pandas import DataFrame

data=[
    {"cd":"A060310", "nm":"3S", "open":2920, "close":2800},
    {"cd":"A095570", "nm":"AJ네트웍스", "open":1920, "close":1900},
    {"cd":"A006840", "nm":"AK홀딩스", "open":2020, "close":2010},
    {"cd":"A054260", "nm":"APK홀딩스", "open":3120, "close":3200}
]
df=DataFrame(data=data)
df=df.set_index('cd')
print(df)

             nm  open  close
cd                          
A060310      3S  2920   2800
A095570  AJ네트웍스  1920   1900
A006840   AK홀딩스  2020   2010
A054260  APK홀딩스  3120   3200


In [145]:
cond=df['open']>=2000
print(df[cond])

             nm  open  close
cd                          
A060310      3S  2920   2800
A006840   AK홀딩스  2020   2010
A054260  APK홀딩스  3120   3200


In [146]:
print(df.query("nm=='3S'"))
print(df.query('nm=="3S"'))

         nm  open  close
cd                      
A060310  3S  2920   2800
         nm  open  close
cd                      
A060310  3S  2920   2800


In [147]:
print(df.query("open>close"))

             nm  open  close
cd                          
A060310      3S  2920   2800
A095570  AJ네트웍스  1920   1900
A006840   AK홀딩스  2020   2010


In [148]:
print(df.query("nm in ['3S', 'AK홀딩스']"))

            nm  open  close
cd                         
A060310     3S  2920   2800
A006840  AK홀딩스  2020   2010


In [149]:
df.query("cd=='A060310'")

nm  open  close
cd                      
A060310  3S  2920   2800

In [150]:
name="AJ네트웍스"
df.query('nm==@name')

nm  open  close
cd                          
A095570  AJ네트웍스  1920   1900

## 5.2 Filter

In [151]:
from pandas import DataFrame

data=[
    [1416, 1416, 2994, 1755],
    [6.42, 17.63, 21.09, 13.93],
    [1.10, 1.49, 2.06, 1.88]
]

columns=["2018/12", "2019/12", "2020/12", "2021/12(E)"]
index=["DPS","PER","PBR"]

df=DataFrame(data=data,index=index,columns=columns)
print(df)

     2018/12  2019/12  2020/12  2021/12(E)
DPS  1416.00  1416.00  2994.00     1755.00
PER     6.42    17.63    21.09       13.93
PBR     1.10     1.49     2.06        1.88


In [152]:
df.filter(items=['2018/12'])

2018/12
DPS  1416.00
PER     6.42
PBR     1.10

In [153]:
df.filter(items=["PER"], axis=0)

2018/12  2019/12  2020/12  2021/12(E)
PER     6.42    17.63    21.09       13.93

In [154]:
df.filter(regex="2020")

2020/12
DPS  2994.00
PER    21.09
PBR     2.06

In [155]:
df.filter(regex="^2020")

2020/12
DPS  2994.00
PER    21.09
PBR     2.06

In [156]:
df.filter(regex="R$", axis=0)

2018/12  2019/12  2020/12  2021/12(E)
PER     6.42    17.63    21.09       13.93
PBR     1.10     1.49     2.06        1.88

In [158]:
df.filter(regex="\d(4)")

Empty DataFrame
Columns: []
Index: [DPS, PER, PBR]

In [159]:
df.filter(regex="\d{4}/\d{2}$")

2018/12  2019/12  2020/12
DPS  1416.00  1416.00  2994.00
PER     6.42    17.63    21.09
PBR     1.10     1.49     2.06

## 5.3 정렬 및 순위

In [161]:
data=[
    ["037730", "3R", 1510],
    ["036360", "3SOFT", 1790],
    ["005670", "ACTS", 1185],
]

columns=["종목코드","종목명","현재가"]
df=DataFrame(data=data, columns=columns)
df.set_index("종목코드", inplace=True)

In [162]:
df2=df.sort_values("현재가")
print(df2)

          종목명   현재가
종목코드               
005670   ACTS  1185
037730     3R  1510
036360  3SOFT  1790


In [163]:
df2=df.sort_values(by="현재가")
print(df2)

          종목명   현재가
종목코드               
005670   ACTS  1185
037730     3R  1510
036360  3SOFT  1790


In [165]:
df2=df.sort_values(by="현재가", ascending=False)
print(df2)

          종목명   현재가
종목코드               
036360  3SOFT  1790
037730     3R  1510
005670   ACTS  1185


In [167]:
df['순위']=df['현재가'].rank()
print(df)

          종목명   현재가   순위
종목코드                    
037730     3R  1510  2.0
036360  3SOFT  1790  3.0
005670   ACTS  1185  1.0


In [168]:
df.sort_values(by="순위", inplace=True)
print(df)

          종목명   현재가   순위
종목코드                    
005670   ACTS  1185  1.0
037730     3R  1510  2.0
036360  3SOFT  1790  3.0


## 5.4 인덱스 연산

In [170]:
import pandas as pd

idx1=pd.Index([1,2,3])
idx2=pd.Index([2,3,4])
print(type(idx1))

<class 'pandas.core.indexes.base.Index'>


In [171]:
idx1.union(idx2)

Index([1, 2, 3, 4], dtype='int64')

In [172]:
idx1.intersection(idx2)

Index([2, 3], dtype='int64')

In [173]:
idx1.difference(idx2)

Index([1], dtype='int64')

## 5.5 GroupBy

In [174]:
from pandas import DataFrame

data=[
    ["2차전지(생산)","SK이노베이션",10.19,1.29],
    ["해운","팬오션",21.23,0.95],
    ["시스템반도체","티엘아이",35.97,1.12],
    ["해운","HMM",21.52,3.20],
    ["2차전지(생산)","LG화확",83.06,3.75]
]

columns=["테마","종목명","PER","PBR"]
df=DataFrame(data=data,columns=columns)
df1=df[df['테마']=="2차전지(생산)"]

In [175]:
df2=df[df['테마']=="해운"]
df3=df[df['테마']=="시스템반도체"]

In [177]:
mean1=df1['PER'].mean()
mean2=df2['PER'].mean()
mean3=df3['PER'].mean()

In [178]:
data=[mean1,mean2,mean3]
index=["2차전지(생산)","해운","시스템반도체"]
s=pd.Series(data=data,index=index)

In [179]:
df.groupby("테마")["PER"].mean()

테마
2차전지(생산)    46.625
시스템반도체      35.970
해운          21.375
Name: PER, dtype: float64

In [180]:
gb=df.groupby("테마")
temp=gb.get_group("2차전지(생산)")
print(temp)

         테마      종목명    PER   PBR
0  2차전지(생산)  SK이노베이션  10.19  1.29
4  2차전지(생산)     LG화확  83.06  3.75


In [182]:
temp=df[["테마","PER","PBR"]].groupby("테마").get_group("2차전지(생산)")
print(temp)

         테마    PER   PBR
0  2차전지(생산)  10.19  1.29
4  2차전지(생산)  83.06  3.75


In [183]:
df.groupby("테마")[["PER","PBR"]].mean()

PER    PBR
테마                     
2차전지(생산)  46.625  2.520
시스템반도체    35.970  1.120
해운        21.375  2.075

In [184]:
df.groupby("테마").mean()  # 종목명 자동제거 오류

TypeError: Could not convert SK이노베이션LG화확 to numeric

In [185]:
df.groupby("테마").agg({"PER":max, "PBR":min})

PER   PBR
테마                   
2차전지(생산)  83.06  1.29
시스템반도체    35.97  1.12
해운        21.52  0.95

In [186]:
import numpy as np
df.groupby("테마").agg({"PER":[min,max], "PBR":[np.std, np.var]})

PER              PBR         
            min    max       std      var
테마                                       
2차전지(생산)  10.19  83.06  1.739483  3.02580
시스템반도체    35.97  35.97       NaN      NaN
해운        21.23  21.52  1.590990  2.53125

## 5.6 좌/우로 붙이기

In [190]:
from pandas import DataFrame
import pandas as pd

# 첫 번째 데이터프레임
data={
    '종가':[113000, 111500],
    '거래량':[555850, 282163]
}
index=['2019-06-21', '2019-06-20']
df1=DataFrame(data=data, index=index)

# 두 번째 데이터프레임
data={
    '시가':[112500,110000],
    '고가':[115000,112000],
    '저가':[111500,109000]
}
index=['2019-06-21','2019-06-20']
df2=DataFrame(data=data, index=index)

df=pd.concat([df1,df2], axis=1)
print(df)

                종가     거래량      시가      고가      저가
2019-06-21  113000  555850  112500  115000  111500
2019-06-20  111500  282163  110000  112000  109000


In [191]:
정렬순서=['시가','고가','저가','종가','거래량']
df=df[정렬순서]
print(df)

                시가      고가      저가      종가     거래량
2019-06-21  112500  115000  111500  113000  555850
2019-06-20  110000  112000  109000  111500  282163


In [192]:
data={
    '종가':[113000, 111500],
    '거래량':[555850, 282163]
}
index=['2019-06-21', '2019-06-20']
df1=DataFrame(data=data, index=index)

data={
    '시가':[112500,110000],
    '고가':[115000,112000],
    '저가':[111500,109000]
}
index=['2019-06-20','2019-06-19']
df2=DataFrame(data=data, index=index)

df=pd.concat([df1,df2], axis=1)
print(df)

                  종가       거래량        시가        고가        저가
2019-06-21  113000.0  555850.0       NaN       NaN       NaN
2019-06-20  111500.0  282163.0  112500.0  115000.0  111500.0
2019-06-19       NaN       NaN  110000.0  112000.0  109000.0


In [193]:
df=pd.concat([df1,df2], axis=1, join='inner')
print(df)

                종가     거래량      시가      고가      저가
2019-06-20  111500  282163  112500  115000  111500


## 5.7 위/아래로 붙이기